name: R-CMD-check

on:
  push:
    branches: [ main, master ]
    paths-ignore:
      - README.md
      - README.Rmd
      - README.html
      - _pkgdown.yml
      - NEWS.md
      - vignettes/**
      - docs/**
      - pkgdown/**
      - man/**
      - inst/extdata/**
  pull_request:
    branches: [ main, master ]
    paths-ignore:
      - README.md
      - README.Rmd
      - README.html
      - _pkgdown.yml
      - NEWS.md
      - vignettes/**
      - docs/**
      - pkgdown/**
      - man/**
      - inst/extdata/**
  workflow_dispatch:

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install system dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            libcurl4-openssl-dev libssl-dev libxml2-dev \
            libfontconfig1-dev libharfbuzz-dev libfribidi-dev \
            libfreetype6-dev libpng-dev libjpeg-dev libtiff5-dev \
            gfortran libudunits2-dev libgdal-dev libgeos-dev libproj-dev

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: >-
            any::rcmdcheck,
            any::roxygen2,
            local::.
          needs: check

      - name: Regenerate Rd with roxygen2
        run: roxygen2::roxygenise()
        shell: Rscript {0}

      - name: Check
        env:
          NOT_CRAN: ""
        run: rcmdcheck::rcmdcheck(args = c("--no-manual", "--as-cran"), error_on = "warning")
        shell: Rscript {0}
